// @description Totally useless... Why on Earth would anyone spam chat with this?
var sizes = [ 'AA', 'A', 'A', 'B', 'B', 'B', 'C', 'C', 'C', 'C', 'D', 'D', 'D', 'DD', 'E', 'F', 'G', 'H' ];
var cupsize = Math.round(5 * Math.round(Math.random() * 12) + 60) + sizes[Math.floor(Math.random() * sizes.length)];
var words = [
	"apples",
	"balloons",
	"bangers",
	"bazooms",
	"bean bags",
	"bon bons",
	"boobies",
	"boulders",
	"bubbies",
	"bumpers",
	"butterbags",
	"canteloupes",
	"eye distractors",
	"gazongas",
	"globes",
	"grapefruits","guavas",
	"hand warmers",
	"hills",
	"honkers",
	"hooters",
	"howitzers",
	"jaboos",
	"jibs",
	"jugs",
	"jumbos",
	"kazongas",
	"knobs",
	"knockers",
	"lactoids",
	"loaves",
	"lollibollies",
	"love bubbles",
	"love muffins",
	"lulus",
	"lungs",
	"mangoes",
	"meatballs",
	"meat loeaves",
	"melons",
	"milk cans",
	"milk shops",
	"milk jugs",
	"mountains",
	"muffines",
	"murphies",
	"nancies",
	"nippers",
	"nodules",
	"noogies",
	"nubbies",
	"oranges",
	"orbs",
	"pair",
	"palookas",
	"papayas",
	"peaches",
	"peaks",
	"pears",
	"pects",
	"peepers",
	"pillows",
	"pokers",
	"pontoons",
	"potatoes",
	"pumpkins",
	"rib cushions",
	"roundies",
	"sandbags",
	"scones",
	"scoops",
	"set",
	"shakers",
	"shimmies",
	"skin sacks",
	"snuggle pups",
	"spheres",
	"spuds",
	"stacks",
	"stuffing",
	"sweater meat",
	"sweet rolls",
	"swingers",
	"tamales",
	"tetons",
	"tidbits",
	"titters",
	"tomatoes",
	"tooters",
	"torpedoes",
	"twangers",
	"twin peaks",
	"umlauts",
	"upper deck",
	"warheads",
	"warts",
	"watermelons",
	"whoppers",
	"wobblers",
	"wongas",
	"yabbos",
	"yams",
	"zeppelins"
];

if (Math.random() < 0.1) {
	response = param + " has no rack at all!";
} else {
	var theword = words[Math.floor(Math.random()*words.length)];
	response = param + " is equipped with " + theword + " of size " + cupsize + ".";
}
response_to = channel;
